### ISSUE TITLE
Build releases on Github?

### ISSUE THREAD

**Issue by poVoq** [Aaron-SP/bds#18]
Would be nice to have the build snapshots and changelog also here on Github. Thanks.

**Comment by Aaron-SP** [comment]
Would keeping a CHANGELOG.md file up to date suffice or are you thinking something else? I added a CHANGELOG.md and plan to update it at each commit, [here](https://github.com/Aaron-SP/bds/commit/2cf0ba956cd317edc04ff7d3197be095ba2c97fd).

**Comment by poVoq** [comment]
Well, actually I would like to add it as an RSS/Atom feed to my open-source game news aggregator and the releases tab in github is very convenient for that (just add .atom to the url). If you could update your website to also provide feeds for the releases and dev-log that would be even better :) Thanks!

**Comment by Aaron-SP** [comment]
I will look into making that information easier to access.

I plan to use the Github releases tab, but want to make sure the first release is stable and well executed. I think we are close to the first release but not quite yet, mainly some game problems need to be addressed. I am not sure if the release will include binaries or not. What time frame would be best between releases? Frequent breaking changes or longer stable changes? 

One thing that is holding me back from a release is user feedback. The more feedback I get, the faster I can make changes and add features.

**Comment by Aaron-SP** [comment]
I have created an RSS XML file that contains the patch updates from the project site [here](https://aaron-sp.github.io/bds/rss.xml).

Let me know if that works for you.

**Comment by poVoq** [comment]
Works great. Thanks!

This is now part of our new (experimental) open-source game news aggregator at freegamedev.net

Any new entries will be pushed to the planet here: https://social.freegamedev.net/channel/planet

You can also follow (and comment on) the feed with any statusnet or activitypub enabled fediverse account like GNUSocial or Mastodon (and of course HubZilla, which is the software we run). Just add planet@social.freegamedev.net to your connections.

P.S.: Posting a bit more descriptions and maybe a screenshot would be awesome :)

**Comment by Aaron-SP** [comment]
I will definitely post pictures for the next one! I am closing this issue out unless you have any other requests.
